
from colorama import Fore, Back, Style
import pyperclip
from os import system
# print(Fore.RED + 'some red text')
# print(Back.GREEN + 'and with a green background')
# print(Style.DIM + 'and in dim text')
# print(Style.RESET_ALL)
# print('back to normal now')

def gen(dist:int, factor:int):
    rtrn = dist**4 / factor + 0.01
    
    return rtrn

def multigen(start:int, end:int, gap:int, factor:int):
    rtrn = []

    dist = start
    while dist <= end:
        rtrn.append([dist, gen(dist, factor)])
        dist += gap

    return rtrn

def multiformat(arr:list):
    rtrn = "radarDetectionCurve\n          {\n            // floatcurve to define at what range (km) which minimum cross section (m^2) can be detected.\n            // this defines both min/max range of the radar, and sensitivity/efficiency\n            // it is recommended to define an \"assured detection range\", at which all craft are detected regardless\n            //     of their rcs. This is achieved by using a minrcs value of zero, thus detecting everything.\n            //        key = distance	rcs"

    lineformat = "\n                      key = %d \t%r"

    rtrn += lineformat.replace("%d", "0").replace("%r", "0")

    for x in range(len(arr)):
        rtrn += lineformat.replace("%d", str(round(arr[x][0],5))).replace("%r", str(round(arr[x][1],5)))
    
    rtrn += "\n\t  } \t// GENERATED BY XBRSQ'S AUTOGENERATOR\n\t    \t// args: " + str(inputStart) + ", " + str(inputEnd) + ", " + str(inputSpace) + ", " + str(inputFactor)

    return rtrn

def get_input():
    global inputStart, inputEnd, inputSpace, inputFactor
    inputStart = int(input("\nStart distance:"))
    inputEnd = int(input("\nEnd distance:"))
    inputSpace = int(input("\nDistance between keys:"))
    inputFactor = int(input("\nDetection factor:"))
    return inputStart,inputEnd,inputSpace,inputFactor

def main():
    system("cls")
    print(Style.BRIGHT+Fore.RED+"VAF RADAR KEY GENERATOR")
    print(Style.NORMAL+Fore.LIGHTRED_EX+"Made by XBRSQ.")
    print(Style.RESET_ALL)

    print(Style.RESET_ALL)
    out = multiformat(multigen(*get_input()))
    pyperclip.copy(out)
    print(Style.DIM+out+Style.RESET_ALL)
    print("Output copied to clipboard")
    input(Back.RED + Fore.BLACK + "Press <ENTER> to exit"+Style.RESET_ALL)
    exit()

if __name__=="__main__":
    main()